#---------------------------------#
#      general configuration      #
#---------------------------------#

version: 1.0.{build}-{branch}

# branches to build
branches:
  # blacklist
  except:
    - gh-pages

#---------------------------------#
#    environment configuration    #
#---------------------------------#

# Operating system (build VM template)
os: Visual Studio 2017

#---------------------------------#
#       build configuration       #
#---------------------------------#

build_script:
  - ps: cd scripts; .\build.ps1 -Compile -verbose

after_build:
  - ps: .\pack.ps1 -verbose

# Disable test search, since we don't have any.
test: off

#---------------------------------#
#           artifacts             #
#---------------------------------#

artifacts:
  - path: build\cmder.zip
    name: cmderzip

  - path: build\cmder.7z
    name: cmder7z

  - path: build\cmder_mini.zip
    name: cmdermini

  - path: build\hashes.txt
    name: hashes

#---------------------------------#
#         notifications           #
#---------------------------------#

notifications:
  # Webhook
  - provider: Webhook
    url: https://webhooks.gitter.im/e/d673abb1b2e659dcd625
    on_build_success: true
    on_build_failure: true
    on_build_status_changed: true
